# Generated by Django 6.0.3 on 2026-03-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('form_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('allowed_departments', models.CharField(blank=True, max_length=255, null=True)),
                ('other_requirements', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
